name: 'Llama3 Issue Triage'

on:
  issues:
    types: [opened, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get labels
        id: get-labels
        run: |
          echo "labels=$(gh label list --json name | jq -r '[.[].name] | join(", ")')" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: ai-action/ollama-action@v1
        id: llama3-labeler
        with:
          model: tinyllama
          prompt: |
            You are an assistant to label GitHub issues. Based on the issue title and body, assign relevant labels from the following list: ${{ steps.get-labels.outputs.labels }}.

            Only reply with a comma-separated list of labels.

            ISSUE TITLE:
            ${{ github.event.issue.title }}

            ISSUE BODY:
            ${{ github.event.issue.body }}
          cache: true
        
      - name: Apply Labels to Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: ${{ steps.llama3-labeler.outputs.response }}
        run: |
          echo "${LABELS}" | tr ',' '\n' | while read label; do
            label=$(echo "$label" | xargs)
            if [ -n "$label" ]; then
              gh issue edit ${{ github.event.issue.number }} --add-label "$label"
            fi
          done
