name: 'Llama3 Issue Triage'

on:
  issues:
    types: [opened, reopened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Get labels
        id: get-labels
        run: |
          echo "labels=$(gh label list --json name | jq -r '[.[].name] | join(", ")')" >> "$GITHUB_OUTPUT"

      - name: Prepare prompt for Llama3
        id: prepare-prompt
        env:
          LABELS: ${{ steps.get-labels.outputs.labels }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          PROMPT="You are an assistant to label GitHub issues. Based on the issue title and body, assign relevant labels from the following list: $LABELS.

          Only reply with a comma-separated list of labels.

          ISSUE TITLE:
          $ISSUE_TITLE

          ISSUE BODY:
          $ISSUE_BODY
          "
          
          echo "prompt<<EOF" >> "$GITHUB_OUTPUT"
          echo "$PROMPT" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Run Llama3 to determine labels
        id: llama3-labeler
        uses: ./.github/actions/llama3-action
        with:
          prompt: ${{ steps.prepare-prompt.outputs.prompt }}

      - name: Apply Labels to Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: ${{ steps.llama3-labeler.outputs.response }}
        run: |
          echo "${LABELS}" | tr ',' '\n' | while read label; do
            label=$(echo "$label" | xargs)
            if [ -n "$label" ]; then
              gh issue edit ${{ github.event.issue.number }} --add-label "$label"
            fi
          done
